# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170719_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='from_book',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
